title: Vatsal Dudhaiya
email: vatsaldudhaiya@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Get to know Vatsal Dudhaiya
baseurl: ""
url: "https://vdudhaiy.github.io"
github_username:  vdudhaiy
linkedin_username: vatsal-dudhaiya
instagram_username: vatsal_dudhaiya

permalink: pretty

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - experience.md
  - projects.md
  - coursework.md
  - more.md
  

collections:
  coursework:
    output: true
    permalink: /coursework/:name/

  projects:
    output: true
    permalink: /projects/:name/
  
  experience:
    output: true
    permalink: /experience/:name/
  
  